=== Subha-saha/WSD_Labs/dom/library.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="University">        
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Library" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Book_Id" type="xs:string"/>
							<xs:element name="Book_name" type="xs:string"/>
							<xs:element name="Author_name" type="xs:string"/>
							<xs:element name="Issue_date" type="xs:string"/> 
							<xs:element name="Return_date" type="xs:string"/>
							<xs:element name="reviews" type="xs:string"/>
						</xs:sequence>
                    </xs:complexType>
                </xs:element>
             </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Subha-saha/WSD_Labs/dom/library.xml
<?xml version="1.0" encoding="UTF-8"?>
<University xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="library.xsd">
   <Library>
      <Book_Id>SE123</Book_Id>
      <Book_name>Software Engineering</Book_name>
      <Author_name>S.chand</Author_name>
      <Issue_date>12-07-2020</Issue_date>
      <Return_date>21-08-2020</Return_date>
      <reviews>7.5</reviews>
   </Library>
   
   <Library>
      <Book_Id>SP231</Book_Id>
      <Book_name>Statistics And Probability</Book_name>
      <Author_name>Ankur Arora</Author_name>
      <Issue_date>01-01-2021</Issue_date>
      <Return_date>22-01-2021</Return_date>
      <reviews>6</reviews>
   </Library>

   <Library>
      <Book_Id>MP342</Book_Id>
      <Book_name>Microprocessor</Book_name>
      <Author_name>A.K Lath</Author_name>
      <Issue_date>03-12-2020</Issue_date>
      <Return_date>09-01-2021</Return_date>
      <reviews>6.5</reviews>
   </Library>

   <Library>
      <Book_Id>LA254</Book_Id>
      <Book_name>Law</Book_name>
      <Author_name>P.C chandra</Author_name>
      <Issue_date>01-12-2007</Issue_date>
      <Return_date>09-08-2012</Return_date>
      <reviews>7.5</reviews>
   </Library>

   <Library>
      <Book_Id>HS123</Book_Id>
      <Book_name>History</Book_name>
      <Author_name>Rabi Bose</Author_name>
      <Issue_date>01-07-2019</Issue_date>
      <Return_date>23-06-2021</Return_date>
      <reviews>9</reviews>
   </Library>

   <Library>
      <Book_Id>MT122</Book_Id>
      <Book_name>MATHS</Book_name>
      <Author_name>R.D Sharma</Author_name>
      <Issue_date>20-02-2002</Issue_date>
      <Return_date>19-12-2002</Return_date>
      <reviews>8</reviews>
   </Library>

   <Library>
      <Book_Id>CAL12</Book_Id>
      <Book_name>Calculus</Book_name>
      <Author_name>R.S Aggarwal</Author_name>
      <Issue_date>05-05-2010</Issue_date>
      <Return_date>21-09-2010</Return_date>
      <reviews>9</reviews>
   </Library>

   <Library>
      <Book_Id>LL456</Book_Id>
      <Book_name>Litreture Learning</Book_name>
      <Author_name>Akhsay Kumar</Author_name>
      <Issue_date>21-06-2008</Issue_date>
      <Return_date>24-07-2008</Return_date>
      <reviews>5</reviews>
   </Library>


</University>
